on:
  push:
    branches:
      - main
  pull_request:
name: lint
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write # to delete cache
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - uses: qawatake/depcache@main
        with:
          dependency-path: go.mod
          path: ~/go/pkg/mod
          skip-save: ${{ github.ref != 'refs/heads/main' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: qawatake/runcache@main
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
          skip-save: ${{ github.ref != 'refs/heads/main' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: make lint
